#!/usr/bin/env bash

# This script runs tests using the JAR artifacts generated by build.sh

echo "=== Running CPU Simulator Tests ==="

# 1. Single-Core

# FCFS (1 core)
echo "FCFS (1 core)"
java -jar build/process-injector.jar --workload workloads/workload.txt | \
  java -jar build/cpu-simulator.jar --cores 1 --scheduler FCFS --ipc pipe

# SJF (1 core)
echo "SJF (1 core)"
java -jar build/process-injector.jar --workload workloads/workload-sjf.txt | \
  java -jar build/cpu-simulator.jar --cores 1 --scheduler SJF --ipc pipe

# PRIO (1 core)
echo "PRIO (1 core)"
java -jar build/process-injector.jar --workload workloads/workload-prio.txt | \
  java -jar build/cpu-simulator.jar --cores 1 --scheduler PRIORITY --ipc pipe

# 2. Multi-Core

# FCFS (4 cores)
echo "FCFS (4 cores)"
java -jar build/process-injector.jar --workload workloads/workload-multicore.txt | \
  java -jar build/cpu-simulator.jar --cores 4 --scheduler FCFS --ipc pipe

# SJF (4 cores)
echo "SJF (4 cores)"
java -jar build/process-injector.jar --workload workloads/workload-multicore.txt | \
  java -jar build/cpu-simulator.jar --cores 4 --scheduler SJF --ipc pipe

# PRIO (4 cores)
echo "PRIO (4 cores)"
java -jar build/process-injector.jar --workload workloads/workload-multicore.txt | \
  java -jar build/cpu-simulator.jar --cores 4 --scheduler PRIORITY --ipc pipe

# # Generate experiment data
# java -cp build/classes com.simulator.utils.WorkloadGenerator --type exp1 --count 25
# java -cp build/classes com.simulator.utils.WorkloadGenerator --type exp2 --count 25
# java -cp build/classes com.simulator.utils.WorkloadGenerator --type exp3 --count 25
